### PR TITLE
Voronoi Pull

### PR DESCRIPTION
**Pull request by CarcerDun**

### CODE REVIEW

**Comment by jceipek** [comment]
@CarcerDun This is awesome and goes far beyond my naive 1:1 AS3 to C# port, but as mentioned in the [README](https://github.com/jceipek/Unity-delaunay#this-repository-is-no-longer-maintained-but-there-are-some-great-alternatives), I am no longer maintaining this project. I'd be happy to accept this PR and make someone else a collaborator, but it may make more sense to continue development at https://github.com/adamgit/Unity-delaunay. What do you think?

**Comment by rainbowdesign** [comment]
https://github.com/adamgit/Unity-delaunay is no longer there. And i assume reading from **https://answers.unity.com/questions/448156/c-simple-voronoidelaunay-diagrams-for-starters.html**

Your link is still what people will find. I suggest to take in the pull request validate and declare the project to be the final version and no more work will be done especially as the code might be lost otherwise.

I am looking for a voronoi treemap to draw game landscapes, but i am not so sure what the repo is without the pull or with, if it is what i am searching i will implement it and tell if it still works.

**Comment by jceipek** [comment]
Thanks for the suggestion, but I just looked over the pull request and it seems that it is actually the version from the now eliminated https://github.com/adamgit/Unity-delaunay, with the extremely worrying comment:

> The original code kept crashing Unity, revealed internal core bugs in Unity. I tried to get Unity corp to accept / fix these, but they refused, so ... I found a better library to work with.

> Use Triangle.net, the open-source C# library that's higher performance with more features. It does delaunay and voronoi.

I've added this suggested alternative to the Readme.

**Comment by rainbowdesign** [comment]
I installed your code i want to make a biome generator. and i need something to draw a biome cluster around the points of interest and then "read" in which biome the field is, sadly i did not really get it working no way to find out in what biome the fields are. Is the project capable of doing this? Or do i better search somewhere else?

**Comment by rainbowdesign** [comment]
I followed the new link: Triangle.net Unity Port has no tutorial of any kind and now suggestion how to start at all and its abandoned so there is no support.

https://scrawkblog.com/2014/06/16/delaunay-triangulation-in-unity/ does timeout.

I have still no idea how to get the points in a voronoi to draw my biomes.

**Pull request closed without merging**
